spring:
  application:
    name: daily-farm-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d1ja7dali9vc739ink3g-a.oregon-postgres.render.com/dailyfarm_8csi}
    username: ${DB_USERNAME:dailyfarm_8csi_user}
    password: ${DB_PASSWORD:BYggZKr4lApq9QiVoDGlRehNeAmyi8aI}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    # show-sql в продакшене отключаем
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        # Для продакшена добавляем диалект, уже не добавляем
        # dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
  #create create-drop update validate - для продакшена
  h2:
    console:
      enabled: false

  output:
    ansi:
      enabled: always
# Порт из переменной окружения (важно для Render!)
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org:
      springframework:
        security: ${SECURITY_LOG:WARN}
      dailyfarm: ${APP_LOG:INFO}
      #web:
      #FilterChainProxy: INFO
      #DEBUG Для продакшена установить уровень логирования обратно на INFO или WARN
#TRACE	всё
#DEBUG	отладки, debug, info, warn, error
#INFO	только info, warn, error
#WARN	warn, error
#ERROR	только error

#   hibernate:
#    orm:
#     jdbc:
#      bind: trace
security:
  jwt:
    secret: ${JWT_SECRET:AYyCFjQxPXt0D97F3iVZeC90rTZqIZxWXiJeboZu8cgXQ4aTE8e0Rgtc7s77AzAM}
    expirationMinutes: ${JWT_EXPIRATION:60}
    refreshExpirationDays: ${REFRESH_EXPIRATION:7}

---
# Профиль для разработки
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# logging для dev профиля - НА КОРНЕВОМ УРОВНЕ
logging:
  level:
    org:
      springframework:
        security: DEBUG
      dailyfarm: DEBUG

---
# Профиль для продакшена
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

# logging для prod профиля - НА КОРНЕВОМ УРОВНЕ
logging:
  level:
    root: WARN
    org:
      dailyfarm: INFO